### ISSUE TITLE
Specify environment for orb container

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/rok8s-scripts#320]
Would be great if we could copy environment variables over from CircleCI over to the orb's executor container

**Comment by sudermanjr** [comment]
This would be a really nice feature.  Basically specify something like this:

```
       - rok8s-scripts/kubernetes_e2e_tests:
           pre_script: e2e/pre.sh
           script: e2e/test.sh
           command_runner_shared_env:
             - CI_SHA1
             - AWS_SECRET_ACCESS_KEY
           filters:
             branches:
               only: /.*/
             tags:
               ignore: /v.*/
```

In this example, CI_SHA1 and AWS_SECRET_ACCESS key would be added to the docker run command for the command runner container and set to the value of env in the circle executor.
