### ISSUE TITLE
External secrets create multiple secrets in k8s

### ISSUE THREAD

**Issue by mariusv** [FairwindsOps/rok8s-scripts#388]
Heya,

If one needs to create multiple Kubernetes secrets from AWS Secrets Manager (for example) can't do it as for now the rok8s-scripts will just pull all secrets in `AWS_SECRETS` and merge them in the `EXTERNAL_SECRETS_K8S_NAME` which will create the Kubernetes secret.

Would be nice to have this option to create multiple k8s secrets from specific AWS/GCP secrets manager.

For now the workaround is to create one secret in k8s and then selectively mount or use the keys as needed.

For example:

```
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      items:
      - key: username
        path: my-group/my-username
```
